---
{% raw %}
- name: Install Python 3
  pkgng: name=python3 state=present
  sudo: true

- name: Create wheelhouse directory
  file: path=/home/vagrant/wheelhouse
        state=directory
        mode=0755

- name: Create .virtualenvs directory
  file: path=/home/vagrant/.virtualenvs
        state=directory
        mode=0755

- name: Check if pip3.4 is installed
  stat: path=/usr/local/bin/pip3.4
  register: pip34

- name: Download get-pip.py
  get_url: url=https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py
           dest=/tmp/get-pip.py
  when: not pip34.stat.exists

- name: Install pip-3.4
  command: python3.4 /tmp/get-pip.py
  sudo: true
  when: not pip34.stat.exists

- name: Updated pip3.4
  command: python3.4 /tmp/get-pip.py
  sudo: true
  when: not pip34.stat.exists

- name: Install wheel
  pip: name=wheel
       state=present
       executable=pip3.4
  sudo: true

- name: Install development requirements
  pip: requirements="/vagrant/requirements.txt"
       executable=pip3.4
       virtualenv_command=pyvenv-3.4
       virtualenv={{ virtualenv_dir }}
       extra_args="-f /home/vagrant/wheelhouse"

- name: Create virtualenv .project file
  lineinfile: dest="{{ virtualenv_dir }}/.project"
              line="/vagrant"
              create=yes

- name: Run manage.py migrate
  django_manage: command="migrate --noinput"
                 app_path=/vagrant
                 settings={{ django_settings_module }}
                 virtualenv={{ virtualenv_dir }}

- name: Run manage.py update_index
  django_manage: command=update_index
                 app_path=/vagrant
                 settings={{ django_settings_module }}
                 virtualenv={{ virtualenv_dir }}
{% endraw %}
