---
-
  hosts: all
  user: vagrant
  sudo: false
  vars:
    env: dev
    project_dir: /vagrant
    project_name: {{ cookiecutter.repo_name }}
    ansible_python_interpreter: /usr/local/bin/python
  roles:
    - vagrant
    - mysql
    - elasticsearch
    - django
