---
{% raw %}
- name: Install Python 3
  pkgng: name=python3 state=present
  sudo: true

- include: pip3.yml

- name: Create virtualenv directory
  file: path={{ virtualenv_dir }}
        state=directory
        mode=0755

- name: Install development requirements
  pip: requirements="{{ project_dir }}/requirements/dev.txt"
       executable=pip3.4
       virtualenv_command=pyvenv-3.4
       virtualenv={{ virtualenv_dir }}
  when: "env == 'dev'"

- name: Install requirements
  pip: requirements="{{ project_dir }}/requirements.txt"
       executable=pip3.4
       virtualenv_command=pyvenv-3.4
       virtualenv={{ virtualenv_dir }}
  when: "env != 'dev'"

- name: Create virtualenv .project file
  lineinfile: dest="{{ virtualenv_dir }}/.project"
              line="{{ project_dir }}"
              create=yes

- name: Run manage.py migrate
  django_manage: command="migrate --noinput"
                 app_path={{ project_dir }}
                 settings={{ django_settings_module }}
                 virtualenv={{ virtualenv_dir }}
  sudo: true
  sudo_user: "{{ app_user }}"

- name: Run manage.py update_index
  django_manage: command=update_index
                 app_path={{ project_dir }}
                 settings={{ django_settings_module }}
                 virtualenv={{ virtualenv_dir }}
  sudo: true
  sudo_user: "{{ app_user }}"

- name: Run manage.py compress
  django_manage: command=compress
                 app_path={{ project_dir }}
                 settings={{ django_settings_module }}
                 virtualenv={{ virtualenv_dir }}
  when: "env != 'dev'"
  sudo: true
  sudo_user: "{{ app_user }}"
{% endraw %}
