---
{% raw %}
- name: uwsgi-start
  supervisorctl: name={{ project_name }}_{{ env }}_uwsgi
                 state=started
                 config=/usr/local/etc/supervisor/conf.d/{{ project_name }}_{{ env }}_uwsgi.conf
{% endraw %}
