---
# Vagrant spesific tasks

- name: Ensure pkg is up to date
  shell: ALWAYS_ASSUME_YES=1 yes | pkg upgrade pkg
  sudo: true

# Required to enable file based locks on NFS shares
- name: Enable lockd
  lineinfile: dest=/etc/rc.conf
              regexp=^rpc_lockd_enable=
              line='rpc_lockd_enable="YES"'
  notify:
    - start lockd
  sudo: true

# Required to enable file based locks on NFS shares
- name: Enable statd
  lineinfile: dest=/etc/rc.conf
              regexp=^rpc_statd_enable=
              line='rpc_statd_enable="YES"'
  notify:
    - start statd
  sudo: true

