---
{% raw %}
- name: Install required system packages.
  pkgng: name=mysql56-server state=present
  sudo: true

- name: Start mysql at startup
  lineinfile: dest=/etc/rc.conf regexp=^mysql_enable= line='mysql_enable="YES"'
  notify:
    - mysql-start
  sudo: true

- name: Start MySQL
  service: name=mysql-server state=started
  sudo: true

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root
              host={{ item }}
              password={{ mysql_root_password }}
              #priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - "%"
    - localhost
  ignore_errors: true
  sudo: true

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: true

- name: delete anonymous MySQL server user for $server_hostname
  mysql_user: user="" host={{ ansible_hostname }} state="absent"
  sudo: true

- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"
  sudo: true

- name: remove the MySQL test database
  mysql_db: db=test state=absent
  sudo: true

- name: Create app database
  mysql_db: db={{ db_name }} state=present
  sudo: true

- name: Create application user
  mysql_user: name={{ db_user }}
              priv="*.*:ALL"
              password={{ db_pass }}
              host={{ item }}
              state=present
  with_items:
    - "{{ ansible_hostname }}"
    - "%"
    - 127.0.0.1
    - ::1
    - localhost
  sudo: true
{% endraw %}
