# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "freebsd-10.1-amd64"
  config.vm.box_url = "http://10.0.0.161:1337/freebsd-10.1-amd64.box"

  #config.vm.synced_folder ".", "/vagrant", :disabled => true

  config.vm.define "webserver" do |webserver|
    # setup private network so we can use nfs
    config.vm.network :private_network, ip: "10.10.0.2"

    # mount application source
    webserver.vm.synced_folder ".", "/vagrant", type: "nfs", id: "vagrant-root", map_uid: 0, map_gid: 0

    # Virtualbox config
    webserver.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end

    # Enable provisioning with ansible
    webserver.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        ansible_python_interpreter: "/usr/local/bin/python",
      }
      ansible.host_key_checking = false
      ansible.playbook = "vagrant/ansible/vagrant.yml"
      ansible.sudo = true
    end
  end
end


